#! /bin/bash

# exit when any command fails
set -e

current=`pwd`

echo "===== Compilation de $1 =====" >&2
echo >&2
echo 1 $1 >&2
echo 2 $2 >&2
cp $1 /tmp/$2
cd /tmp/
gnatmake -I${current}/IncludeGada -I${current}/IncludeExosS1 -I${current}/IncludeExosS2 /tmp/${2:-$1} -o /tmp/exe


echo
echo
echo "===== Exécution de $1 ====="
echo
/tmp/exe 2>&1

